### ISSUE TITLE
cr/lf behavior

### ISSUE THREAD

**Issue by sbelectronics** [jim11662418/8008-SBC#2]
Hello Jim,
I'm designing a project based on your 8008-SBC, trying out the ROM images, and have run into something that puzzles me. Everything works fine, but...

1) basic newlines output linefeeds without carriage returns
2) monitor newlines output carriage returns without linefeeds

To say it another way, I get a 0x0A at the end of every basic line, and I get a 0x0D at the end of each monitor line. The code leads me to believe I should see 0x0D, 0X0A.

This is using your HEX files checked into git. I'm going to try to reassemble the source myself and maybe do some debugging, but I also wanted to check with you to see if it was a known issue. Thanks, Scott.

**Comment by sbelectronics** [comment]
Well this was easier resolved than I expected. Turns out monitor.asm had many of the strings terminated with `\r` whereas scelbal-in-eprom.asm had them terminated with `\n`. I modified them all to use `\r\n` and reassembled. All is working well now.

**Comment by jim11662418** [comment]
Glad you found the problem. Good luck with your project.

**Comment by jim11662418** [comment]
Thinking about it I guess I never noticed the problem because I had been
using Teraterm which supplies the missing line feed or carriage return as
the case may be.

**Comment by sbelectronics** [comment]
Thanks., yeah, my terminal (securecrt) had options to automatically add CRs or automatically add LFs, but no option that simultaneously handled both cases... so it stood out immediately. :)

I also wanted to point out a potential bug here: https://github.com/jim11662418/8008-SBC/blob/e9ff7901b306790919fe962af8040f1413ed851b/8008SBC_1.PLD#L45. Maybe you meant S2 for the first term?

Have you had any issues with the 1000 digit pi program? The 100 digit program generated a plausible answer, but the 1000 is generating a value that looks clearly incorrect.

**Comment by sbelectronics** [comment]
Also, I've modified the PLDs and the monitor to suit my project. Do you have any objection to my publishing the modified source code, for noncommercial purposes? I didn't see a specific license file.

**Comment by jim11662418** [comment]
1. You're correct about the typo in the equation for the T3 state. Luckily
it didn't cause any issues.
2. I do seem to remember that the output of the 1000 digit pi
generating program didn't seem quite right. At the time, however, since I
didn't understand (and still don't) how they work, I was just happy to get
any output.
3. No objections to your publishing your modifications to the source code.
In fact, I'm curious to see the changes you've made.

**Comment by jim11662418** [comment]
I saw the write-up in Hackaday about your H8 8008 CPU board. Very cool!
